import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Bazar-Dor-Web',
  description: 'Generated by Shahidul',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html data-theme="light" lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <div className="lg:h-50 h-35 mb-3">
          <div className="fixed top-0 left-0 z-50 w-full bg-white shadow-sm">
            <Navbar />
          </div>
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
